export const benchmarkBriefs = [
  {
    id: "cinematic-saas-hero",
    title: "Cinematic SaaS Hero",
    brandName: "Northstar",
    siteType: "single-page SaaS hero",
    audience: "founders evaluating premium software",
    goal: "prove the product is credible in the first viewport",
    visualDirection: "cinematic video background, restrained glass controls, clear product promise",
    stack: "React + TypeScript + Vite + Tailwind CSS",
    assets: "exact looping video URL, logo wordmark, desktop and mobile screenshot QA",
    constraints: "no placeholder assets, no decorative blobs, no text overlap",
  },
  {
    id: "ai-dashboard",
    title: "AI Dashboard Surface",
    brandName: "Metricflow",
    siteType: "analytics dashboard landing page",
    audience: "operations leaders and data teams",
    goal: "show product depth without marketing fluff",
    visualDirection: "dense but calm dashboard proof, neutral palette, readable metrics",
    stack: "React + TypeScript + Tailwind CSS + lucide-react",
    assets: "mock dashboard panels, charts, exact empty/loading/error states",
    constraints: "no oversized hero-only marketing page; prioritize scanability",
  },
  {
    id: "agency-portfolio",
    title: "Agency Portfolio Hero",
    brandName: "Atelier",
    siteType: "creative studio portfolio",
    audience: "brand teams looking for a design partner",
    goal: "feel editorial, premium, and implementation-ready",
    visualDirection: "full-screen video, expressive serif headline, mobile menu, case-study cues",
    stack: "React + TypeScript + Vite + Tailwind CSS",
    assets: "exact video URL, project thumbnails, accessible navigation states",
    constraints: "no generic agency copy; visible first-screen signal of craft",
  },
  {
    id: "signup-flow",
    title: "Conversion Signup Flow",
    brandName: "Aurora",
    siteType: "two-column registration interface",
    audience: "new users onboarding into a premium app",
    goal: "make signup feel trustworthy and fast",
    visualDirection: "video-supported left rail, clean form right rail, progress steps",
    stack: "React + TypeScript + Tailwind CSS + motion/react",
    assets: "background video, social icons, password visibility toggle",
    constraints: "no external auth wiring; form states must fit on mobile",
  },
  {
    id: "commerce-product",
    title: "Commerce Product Hero",
    brandName: "CozyPaws",
    siteType: "pet commerce hero",
    audience: "mobile shoppers comparing product quality",
    goal: "sell the product with proof, not a landing-page brochure",
    visualDirection: "warm product photography, compact cards, offer and rating proof",
    stack: "React + TypeScript + Vite + Tailwind CSS",
    assets: "product image URL, price/rating chips, responsive cart CTA",
    constraints: "avoid one-note beige palette and generic stock placeholders",
  },
  {
    id: "fintech-trust",
    title: "Fintech Trust Hero",
    brandName: "Harbor",
    siteType: "stablecoin product landing page",
    audience: "finance operators and technical buyers",
    goal: "communicate trust, compliance, and product clarity",
    visualDirection: "quiet fintech layout, proof badges, card/account visual",
    stack: "React + TypeScript + Tailwind CSS",
    assets: "logo, product mock, compliance badges, motion states",
    constraints: "no hype crypto language; accessibility and contrast required",
  },
  {
    id: "wellness-video",
    title: "Wellness Video Hero",
    brandName: "Aurai",
    siteType: "AI wellness companion hero",
    audience: "people seeking calm support",
    goal: "feel personal, private, and safe",
    visualDirection: "fullscreen video without dark overlay, glass email capture, feature pills",
    stack: "React + TypeScript + Tailwind CSS + lucide-react",
    assets: "exact video URL, custom SVG logo, email form states",
    constraints: "no clinical overclaiming; protect mobile readability",
  },
  {
    id: "education-platform",
    title: "Education Platform Hero",
    brandName: "DesignPro",
    siteType: "product design education landing page",
    audience: "emerging designers choosing a cohort",
    goal: "make the program feel selective and career-ready",
    visualDirection: "dark video hero, shiny headline treatment, cohort proof stats",
    stack: "React + TypeScript + Tailwind CSS + Framer Motion",
    assets: "exact video URL, animated gradient headline, application CTA",
    constraints: "motion must be purposeful and responsive",
  },
  {
    id: "feature-section",
    title: "Core Feature Cards",
    brandName: "Viktor",
    siteType: "three-card marketing feature section",
    audience: "builders evaluating an image-generation tool",
    goal: "show concrete product capabilities in one section",
    visualDirection: "gradient cards, exact SVG/image assets, no animation",
    stack: "React + TypeScript + plain CSS or Tailwind CSS",
    assets: "network SVG, folder SVG, cursor icon, search icon",
    constraints: "static component, no hover behavior, exact card dimensions",
  },
  {
    id: "error-page",
    title: "404 Hero Page",
    brandName: "Wayfinder",
    siteType: "full-viewport error page",
    audience: "users who hit a missing route",
    goal: "recover gracefully with a polished empty state",
    visualDirection: "minimal full-screen layout, useful navigation, subtle motion",
    stack: "React + TypeScript + Tailwind CSS",
    assets: "brand mark, background visual, home/search actions",
    constraints: "100vh no scroll, accessible focus states, no dead CTAs",
  },
];
